# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctt < Formula
  desc ""
  homepage "https://github.com/odedpriva/cli-transparent-tunnel"
  version "0.0.1-rc5"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odedpriva/cli-transparent-tunnel/releases/download/v0.0.1-rc5/cli-transparent-tunnel_0.0.1-rc5_Darwin_arm64.tar.gz"
      sha256 "a35052efec7893ba672d2cd9358b46209d24a0740672c4e1fec1d917bd43414c"

      def install
        bin.install "ctt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odedpriva/cli-transparent-tunnel/releases/download/v0.0.1-rc5/cli-transparent-tunnel_0.0.1-rc5_Darwin_amd64.tar.gz"
      sha256 "572a0bb09a080f5ed7caae1508688c112be630145cc2e8c5f7ce8f17a65a7270"

      def install
        bin.install "ctt"
      end
    end
  end

  depends_on "kubectl"
end
